### ISSUE TITLE
Having to re-authenticate on page refresh

### ISSUE THREAD

**Issue by antoinerg** [eXist-db/eXide#3] opened 2012-01-30 18:01 UTC
How come do I have to re-authenticate whenever I refresh the page?  Isn't my username saved server-side in the HTTP session?

**Comment by joewiz** [comment] 2017-02-24 17:25
I see this intermittently but have not been able to come up with a reproducible test. I'm inclined to close this unless we're able to come up with a test. Please let us know if you have any further insights.

**Comment by dizzzz** [comment] 2017-02-24 18:26
The issue is 6 years old, eXistdb is a different product right now

**Comment by joewiz** [comment] 2017-02-24 22:02
Agreed, let's close and look for any reproducible reports.

**Closed as completed by joewiz** 2017-02-24 22:02 UTC

**Comment by wshager** [comment] 2017-02-24 22:12
Still not fixed

**Comment by joewiz** [comment] 2017-02-24 22:14
Right, like I said, I still see this intermittently. But we need a reproducible report. Do you have one?

**Comment by wshager** [comment] 2017-02-24 22:17
Why close this ticket then?

Op 24 feb. 2017 23:14 schreef "Joe Wicentowski" <notifications@github.com>:

**Comment by joewiz** [comment] 2017-02-24 22:21
Insufficient detail.

**Comment by dizzzz** [comment] 2017-02-25 09:43
the ticket is rather unclear and unspecific. it makes no sense to try to understand the exact conditions.... waste of time.
