### ISSUE TITLE
[BUG] Exist 5.3.0 can't create application

### ISSUE THREAD

**Issue by mwindrath** [eXist-db/eXide#338] opened 2021-07-23 12:50 UTC
> To be able to better understand you problem, please add as much information as possible to this ticket. Always test your bugs against the latest stable release of exist. We cannot provide support for older versions here on GitHub. If the version of eXist that is experiencing the issue is more than 1 major version behind the most recent release, please consider posting a question on our mailing list. 

**Describe the bug**
Using Windows 10 and Java 8 Build 291, the latest JAR exist Installer, 5.3.0, i wasnt able to create applications using Exide. The needed button wasn't displayed.

[https://imgur.com/v3aSZ84](url)

I haven't made any changes after the installation (e.g. conf.xml). I created only a directory for the database.

I had tried to reinstall exist but it doesn't changend.

To reproduce: Install exist 5.3.0 using jar and go to exide. Select application.

I Installed exist 5.2.0 and it works there.

**Comment by duncdrum** [comment] 2021-07-23 19:39
Duplicate of #323 please see the responses there. This is not a bug.

**Closed as completed by duncdrum** 2021-07-23 19:39 UTC
